[project]
name = "aio-processor"
version = "0.1.0"
description = "AI media processing toolkit"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.3.0 ; sys_platform == 'win32' and platform_machine == 'AMD64'",
    "torchvision>=0.18.0",
    "torchmetrics>=1.4.0",
    "torchaudio>=2.3.0",
    "transformers>=4.41.0",
    "qwen-vl-utils>=0.1.0",
    "accelerate>=0.30.1",
    "librosa>=0.10.2",
    "opencv-python>=4.9.0.80"
]

[tool.uv.sources]
pytorch = { url = "https://download.pytorch.org/whl/cu121" }

[tool.uv]
pip-version = "24.0"
resolution = "lowest-direct"
python = "3.12"
linker = "clone"

[build-system]
requires = ["uv>=0.1.0"]
build-backend = "uv"
